### ISSUE TITLE
trojan virus detected in windows exe format

### ISSUE THREAD

**Issue by 94maldini** [Yazaar/StreamElements-Local-Cloudbot#5]
I am using Windows 10 and a trojan virus was detected. Is this a trap?

**Comment by Yazaar** [comment]
I am using [pyinstaller](https://www.pyinstaller.org) to create an executable. Why it flags it as a trojan am I not entirely sure, in the bin folder can `Windows.exe` and `Windows.py` be found which are identical applications (only that the `.exe` is frozen). You can for sure install python and run LSE without the executable and this way you can see what you are running ([getting started guide](https://github.com/Yazaar/StreamElements-Local-Cloudbot/wiki/Getting-started))

**Comment by Yazaar** [comment]
Uploaded the Windows.exe file to [VirusTotal](https://www.virustotal.com) and it did indeed trigger in 2 out of 69 cases. [Here](https://www.virustotal.com/gui-dev/file/38c16540408e75fb32f16ce58aa43a720ce0a838f4aec7e927659382464d19b2/detection) is the result for the false positive.

**Comment by Yazaar** [comment]
Pushed an update for the executable (Windows.exe) but might lead to more problems according to [this](https://www.virustotal.com/gui/file/7ccc012512d6f19f76f86434a9a6c41957777025c7adc3dcc1fba2512869e9c7/detection) result from VirusTotal. But worth a try since the other one did not work properly either. Would strongly recommend downloading python instead of using the executable though.
